#This compose file is for producing the production image
version: "3"
services:
  turfcoach_scheduler_app:
    build:
      context: ../
      dockerfile: ./docker/dockerfile.prod.yml
    working_dir: /home/node/app
    # Set the MONGO URI to a file so that it can be read from the secrets manager.
    environment:
      - PORT=8080
      - NODE_ENV=production
      - MONGO_URI_FILE=/run/secrets/db_mongo_uri
    ports:
      - "8080:8080"
    secrets:
      - db_mongo_uri
    depends_on:
      - app_database

  app_database:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/db_username
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/db_password
    ports:
      - "27017:27017"
    secrets:
      - db_username
      - db_password
    volumes:
      - mongo-data:/data/db

secrets:
  db_username:
    file: ../environment/db_root_username.env
  db_password:
    file: ../environment/db_root_password.env
  db_mongo_uri:
    file: ../environment/db_mongo_uri.env
volumes:
  mongo-data:
